inherit_from:
  - .rubocop2.yml

AllCops:
  Exclude:
    - ./**/aaaa/**/*.rb
  Severity:
    warning: 'refactor'

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout:
  Exclude:
    - ./**/bbbb/**/*.rb
  TrailingWhitespace:
    Enabled: false
