/* Prototype generated schema header for Layout */
#ifndef LEUKO_CONFIGS_SCHEMA_LAYOUT_H
#define LEUKO_CONFIGS_SCHEMA_LAYOUT_H

/* This header is generated by scripts/generate_schema.py (prototype).
   It exists to allow building experimental schema-driven loader. */

#include <stdbool.h>

/* Runtime entrypoint (prototype) */
bool leuko_schema_layout_enabled(void);

#endif /* LEUKO_CONFIGS_SCHEMA_LAYOUT_H */
